USE [master]
GO

/****** Object:  Database [PROJEKT (grupa 4)]    Script Date: 21.04.2020 15:34:12 ******/
CREATE DATABASE [PROJEKT (grupa 4)]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PROJEKT (grupa 4)', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.KWZP2020\MSSQL\DATA\PROJEKT (grupa 4).mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PROJEKT (grupa 4)_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.KWZP2020\MSSQL\DATA\PROJEKT (grupa 4)_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PROJEKT (grupa 4)].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET ARITHABORT OFF 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET RECOVERY FULL 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET  MULTI_USER 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PROJEKT (grupa 4)] SET  READ_WRITE 
GO

