//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dostawy_Wlasne_Zawartosc
    {
        public int ID_Dostawy_Wlasne_Zawartosc { get; set; }
        public Nullable<int> ID_Zamowienia_dostawy_wlasne { get; set; }
        public Nullable<int> ID_Dostawy { get; set; }
        public Nullable<int> ID_Element { get; set; }
        public Nullable<int> Ilosc { get; set; }
    
        public virtual Zamowienia_Dostawy Zamowienia_Dostawy { get; set; }
        public virtual Elementy Elementy { get; set; }
        public virtual Zamowienia_Dostawy_Wlasne Zamowienia_Dostawy_Wlasne { get; set; }
    }
}
