//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dostarczenia_Wewn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dostarczenia_Wewn()
        {
            this.Odbior_Dostarczenia = new HashSet<Odbior_Dostarczenia>();
        }
    
        public int ID_Dostarczenia { get; set; }
        public Nullable<int> ID_Pracownicy { get; set; }
        public Nullable<int> ID_Dostawy { get; set; }
        public Nullable<int> ID_Zamowienie_element { get; set; }
        public Nullable<int> ID_element { get; set; }
        public Nullable<double> Ilosc_Dostarczona { get; set; }
        public Nullable<int> ID_Miejsca { get; set; }
        public string Data_Dostarczenia { get; set; }
    
        public virtual Zamowienia_Dostawy Zamowienia_Dostawy { get; set; }
        public virtual Elementy Elementy { get; set; }
        public virtual Miejsca Miejsca { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odbior_Dostarczenia> Odbior_Dostarczenia { get; set; }
    }
}
