//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odbior_Dostarczenia
    {
        public int ID_Odbior_Dostarczenia { get; set; }
        public int ID_Procesu_Produkcyjnego { get; set; }
        public int ID_Dostarczenia { get; set; }
        public Nullable<bool> Odebrano { get; set; }
    
        public virtual Dostarczenia_Wewn Dostarczenia_Wewn { get; set; }
        public virtual Proces_Produkcyjny Proces_Produkcyjny { get; set; }
    }
}
