//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Typy_cechy_rejestr
    {
        public int ID_Typy_Cechy { get; set; }
        public Nullable<int> ID_typ { get; set; }
        public Nullable<int> ID_cecha { get; set; }
    
        public virtual Elementy_Cechy_Slownik Elementy_Cechy_Slownik { get; set; }
        public virtual Elementy_Typy Elementy_Typy { get; set; }
    }
}
