//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBilans
    {
        public long id { get; set; }
        public Nullable<double> Zysk_brutto { get; set; }
        public string Podatek_liniowy { get; set; }
        public Nullable<double> Zysk_netto { get; set; }
    }
}
