//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCechyElementu
    {
        public int ID { get; set; }
        public string Cecha { get; set; }
        public Nullable<float> Wartosc_liczbowa { get; set; }
        public string Jednostka { get; set; }
    }
}
