//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCenaZaMaterial
    {
        public int ID_Zamowienia { get; set; }
        public Nullable<float> Ilosc_Paczek { get; set; }
        public string Element_Nazwa { get; set; }
        public Nullable<decimal> Cena_Jedn { get; set; }
        public Nullable<float> Ilosc_W_Opakowaniu_Pojedynczym { get; set; }
        public Nullable<double> Cena_za_material { get; set; }
    }
}
