//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDokumentacja_info
    {
        public int Numer_procesu { get; set; }
        public string Rodzaj { get; set; }
        public string Imię_i_nazwisko { get; set; }
        public System.DateTime Data_wykonania { get; set; }
    }
}
