//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDostawyNiewydaneZPolkamiNiesumowane
    {
        public Nullable<int> ID_Zamowienia { get; set; }
        public int ID_Dostawy { get; set; }
        public int ID_Element { get; set; }
        public string Element_Nazwa { get; set; }
        public Nullable<int> Ilosc { get; set; }
        public Nullable<System.DateTime> Proponowana_data_dostawy_materialu { get; set; }
    }
}
