//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vElementyProcesProdukcyjny
    {
        public int ID_Procesu_Produkcyjnego { get; set; }
        public int ID_Zamowienie_Element { get; set; }
        public int ID_Elementy_Proces { get; set; }
        public string Element { get; set; }
        public int ID_Element { get; set; }
        public string Element_Nazwa { get; set; }
        public int Liczba { get; set; }
        public int ID_jednostka { get; set; }
        public string Jednostka { get; set; }
    }
}
