//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFaktury
    {
        public int ID_Zamowienia { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public Nullable<int> Calkowity_koszt_produkcji { get; set; }
        public Nullable<decimal> Cena_netto { get; set; }
        public Nullable<decimal> Cena_brutto { get; set; }
    }
}
