//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vKlienci
    {
        public int Numer_klienta { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Nazwa_firmy { get; set; }
        public string NIP { get; set; }
        public string Adres { get; set; }
        public string Odleglosc_w_km { get; set; }
        public string Telefon { get; set; }
        public string e_mail { get; set; }
    }
}
