//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vKompletnyProces
    {
        public int ID_Zamowienie_Element { get; set; }
        public Nullable<int> ID_Procesu_Produkcyjnego { get; set; }
        public Nullable<bool> Kompletny_Proces { get; set; }
    }
}
