//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vKontrolaProcesu
    {
        public int ID_procesu_produkcyjnego { get; set; }
        public Nullable<int> ID_zamówienia { get; set; }
        public string Nazwa_elementu { get; set; }
        public int Ilość { get; set; }
        public Nullable<int> Liczba_poprawnych { get; set; }
        public string Status_produktów { get; set; }
        public Nullable<int> Bilans_produktów { get; set; }
        public Nullable<System.DateTime> Data_kontroli { get; set; }
    }
}
