//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vMaszyny_proces
    {
        public int Numer_procesu { get; set; }
        public string Rodzaj_maszyny { get; set; }
        public int Liczba_maszyn { get; set; }
        public int Liczba_roboczogodzin_maszyny { get; set; }
        public int Koszt_roboczogodziny_maszyny { get; set; }
    }
}
