//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vNieuzytyMaterialOdpad
    {
        public Nullable<int> ID_Zamowienia { get; set; }
        public int ID_Zamowienie_Element { get; set; }
        public int ID_Materiału_Na_Produkcji { get; set; }
        public int ID_Procesu_Produkcyjnego { get; set; }
        public int ID_Elementy_Procesu { get; set; }
        public int ID_Element { get; set; }
        public string Nazwa_Elementu { get; set; }
        public string Jednostka { get; set; }
        public Nullable<double> Odpad { get; set; }
        public Nullable<double> Nieużyty_Materiał { get; set; }
        public Nullable<bool> Magazyn_Odebrał_Materiał { get; set; }
        public Nullable<System.DateTime> Data_Zakończenia { get; set; }
    }
}
