//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPolki_Rozmiary
    {
        public int ID_Rozmiar_Polki { get; set; }
        public Nullable<int> Wysokosc { get; set; }
        public Nullable<int> Szerokosc { get; set; }
        public Nullable<int> Glebokosc { get; set; }
        public Nullable<int> Wymiar { get; set; }
    }
}
