//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProces_technologicznyy
    {
        public Nullable<int> ID_Zamowienia { get; set; }
        public int Numer_elementu { get; set; }
        public int Numer_procesu { get; set; }
        public Nullable<bool> Kompletny_proces { get; set; }
    }
}
