//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProces_technologiczny
    {
        public int Numer_zamówienia { get; set; }
        public int Numer_elementu { get; set; }
        public string Element_Nazwa { get; set; }
        public int Ilosc { get; set; }
    }
}
