//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProduktyWykonane
    {
        public Nullable<System.DateTime> Data_Zakonczenia { get; set; }
        public int ID_Zamowienia { get; set; }
        public Nullable<int> ID_Element { get; set; }
    }
}
