//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProces_Maszyna
    {
        public int ID_Proces_Technologiczny { get; set; }
        public string Rodzaj_Maszyny { get; set; }
        public int Liczba_Maszyn { get; set; }
        public int Liczba_Rbh_Maszyna { get; set; }
    }
}
