//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRegaly
    {
        public string Oznaczenie { get; set; }
        public int ID_Polka { get; set; }
        public string Element_Nazwa { get; set; }
        public Nullable<int> Ilosc_Paczek { get; set; }
        public string Jednostka { get; set; }
    }
}
