//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSzacowanyCzasWykonania
    {
        public long id { get; set; }
        public string Typ { get; set; }
        public Nullable<System.DateTime> Szacowany_czas_wykonania { get; set; }
    }
}
