//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vUrlopPracownika
    {
        public int ID_Pracownika { get; set; }
        public System.DateTime Data_rozpoczecia { get; set; }
        public System.DateTime Data_zakonczenia { get; set; }
        public string Nazwa { get; set; }
    }
}
