//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vWszystkie_Maszyny
    {
        public int Numer_maszyny { get; set; }
        public string Rodzaj_maszyny { get; set; }
        public string Producent { get; set; }
        public string Numer_seryjny { get; set; }
    }
}
