//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vWydawanie_Zamowien_Kurierowi
    {
        public Nullable<int> ID_Zamowienia { get; set; }
        public int ID_Zamowienie_Element { get; set; }
        public string Element_Nazwa { get; set; }
        public Nullable<int> ID_element { get; set; }
        public Nullable<double> Ilosc { get; set; }
    }
}
