//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vZawartoscZIloscia
    {
        public int ID_Zawartosc { get; set; }
        public Nullable<int> ID_Polka { get; set; }
        public Nullable<int> ID_Element { get; set; }
        public Nullable<int> ID_Dostawy { get; set; }
        public Nullable<int> ID_Zamowienia { get; set; }
        public Nullable<double> Ilosc { get; set; }
    }
}
