//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szwalnia
{
    using System;
    using System.Collections.Generic;
    
    public partial class vZawartosc_polki
    {
        public int ID_Regal { get; set; }
        public string Oznaczenie { get; set; }
        public Nullable<int> ID_Polka { get; set; }
        public string Element_Nazwa { get; set; }
        public Nullable<float> Ilosc_Paczek { get; set; }
        public Nullable<float> Ilosc_W_Opakowaniu_Pojedynczym { get; set; }
        public string Jednostka { get; set; }
        public Nullable<float> Ile_sztuk { get; set; }
    }
}
